# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eeg_plot.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1552, 877)
        self.xyz_plot = GraphicsLayoutWidget(Form)
        self.xyz_plot.setGeometry(QtCore.QRect(220, 180, 1321, 661))
        self.xyz_plot.setObjectName("xyz_plot")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(20, 29, 181, 561))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 71, 31))
        self.label_2.setObjectName("label_2")
        self.amp_x = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.amp_x.setGeometry(QtCore.QRect(50, 60, 62, 21))
        self.amp_x.setMinimum(0.01)
        self.amp_x.setMaximum(100000.0)
        self.amp_x.setProperty("value", 1.0)
        self.amp_x.setObjectName("amp_x")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 31, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 31, 31))
        self.label_4.setObjectName("label_4")
        self.amp_y = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.amp_y.setGeometry(QtCore.QRect(50, 100, 62, 21))
        self.amp_y.setMinimum(-1000.0)
        self.amp_y.setMaximum(10000.0)
        self.amp_y.setProperty("value", -1.0)
        self.amp_y.setObjectName("amp_y")
        self.amp_submit = QtWidgets.QPushButton(self.groupBox)
        self.amp_submit.setGeometry(QtCore.QRect(10, 140, 75, 23))
        self.amp_submit.setObjectName("amp_submit")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 190, 101, 16))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.label_5.setObjectName("label_5")
        self.start_channel_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.start_channel_spinBox.setGeometry(QtCore.QRect(80, 220, 42, 22))
        self.start_channel_spinBox.setMaximum(10000)
        self.start_channel_spinBox.setObjectName("start_channel_spinBox")
        self.channel_submit_2 = QtWidgets.QPushButton(self.groupBox)
        self.channel_submit_2.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.channel_submit_2.setObjectName("channel_submit_2")
        self.engry_plot = GraphicsLayoutWidget(Form)
        self.engry_plot.setGeometry(QtCore.QRect(220, 40, 1041, 131))
        self.engry_plot.setObjectName("engry_plot")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "波形展示"))
        self.groupBox.setTitle(_translate("Form", "GroupBox"))
        self.label_2.setText(_translate("Form", "Y轴幅值"))
        self.label_3.setText(_translate("Form", "max:"))
        self.label_4.setText(_translate("Form", "min:"))
        self.amp_submit.setText(_translate("Form", "调整"))
        self.label.setText(_translate("Form", "调整显示的通道"))
        self.label_5.setText(_translate("Form", "开始的通道"))
        self.channel_submit_2.setText(_translate("Form", "调整"))
from pyqtgraph import GraphicsLayoutWidget
